resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: gups-repo
    type: git
    source:
      uri: https://github.com/avanier/gups
      branch: feature/add-ci-pipeline
      tag_filter: '*.*.*'
      check_every: 24h

  - name: gups-image
    type: docker-image
    source:
      repository: registry.hub.docker.com/adgear/gups
      username: ((dockerhub.username))
      password: ((dockerhub.access_token))

  - name: slack
    type: slack-notification
    source: { url: ((slack-ci-cd-lab)) }

jobs:
  - name: build-image
    plan:
      - get: gups-repo
        version: every
        trigger: true

      - task: generate-metadata
        file: gups-repo/ci/tasks/generate-metadata.yml

      - put: gups-image
        params:
          build: gups-repo
          tag_file: build-metadata/tag
          additional_tags: build-metadata/additionnal_tags
          labels_file: build-metadata/labels.json
          tag_as_latest: true

      - put: slack
        params:
          text_file: build-metadata/tag
          text: Success!
          attachments:
            - text: ":gupi-chan: Version <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|$TEXT_FILE_CONTENT> of gups was released"
              color: "good"
